### ISSUE TITLE
Error: service php5-fpm restart returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by bobweston** [jippi/puppet-php#153]
I recently had to upgrade ubuntu from 12.04 (where everything was working) to 14.04. Since then, I'm seeing intermittent errors about not being able to start php5-fpm.
Here's the error:

error:
==> appServer: Error: service php5-fpm restart returned 1 instead of one of [0]
==> appServer: Error: /Stage[main]/Projects::Interact::Servers::App::Php/Exec[restart-php5-fpm]/returns: change from notrun to 0 failed: service php5-fpm restart returned 1 instead of one of [0]
```puppet
exec { "restart-php5-fpm":
  command  => "service php5-fpm restart",
  schedule => hourly,
  require => [Class[php::fpm], Package['php5-fpm'],
             Class[projects::interact::shared::packages], Package[$php_modules]]
}
```
I'm fairly new to this and would really appreciate any help or suggestions anyone might have to resolve this.

**Comment by igalic** [comment]
`schedule => hourly` ??


i didn't know we're using schedule.

**Comment by schkovich** [comment]
@bobweston That is not the way how to use metaparameter [schedule](https://docs.puppetlabs.com/puppet/latest/reference/metaparameter.html#schedule).

```puppet
schedule { 'fpm':
  period => hourly,
  repeat  => 1,
}

exec { "restart php5-fpm":  // It is Upstart job in Ubuntu 14.04
  schedule => 'fpm',
}
```
Find more details [here](http://docs.puppetlabs.com/puppet/latest/reference/type.html#schedule).

I curious: Which problem are you trying to solve? Why would you restart fpm every hour?

@igalic I would suggest closing the issue since the problem has nothing to do with _puppet-php_ module except that except dependency on class ```php::fpm```.
